# Generated by Django 3.1.7 on 2021-04-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.key')),
            ],
        ),
        migrations.CreateModel(
            name='ThisWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.key')),
            ],
        ),
    ]
