# Generated by Django 3.1.7 on 2021-04-02 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210401_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='thisweek',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thisweek',
            name='end_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisweek',
            name='start_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='today',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='today',
            name='today',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
