# Generated by Django 3.1.7 on 2021-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210402_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thisweek',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='today',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
